# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  (1..3).each do |i|
    config.vm.define "Node-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.synced_folder ".", "/vagrant", disabled: true

      config.vm.provider "virtualbox" do |vb|
        # Customize the amount of memory on the VM:
        vb.name   = "Name of your project - Node #{i}"
        vb.memory = "512"
        vb.cpus   = "1"
      end
    end
  end
end
