Vagrant.configure(2) do |config|
  config.vm.define "n1" do |n1|
      n1.vm.box = "centos/7"
      n1.vm.synced_folder ".", "/vagrant", disabled: true
      n1.vm.hostname = "n1"
      n1.vm.network "private_network", ip: "172.20.20.10"
  end

  config.vm.define "n2" do |n2|
      n2.vm.box = "centos/7"
      n2.vm.synced_folder ".", "/vagrant", disabled: true
      n2.vm.hostname = "n2"
      n2.vm.network "private_network", ip: "172.20.20.11"
      config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbook.yml"
      end
  end
end
